In [1]:
import torch

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [2]:
x = torch.zeros(8,8)
arr = torch.Tensor([-4.0, -3.0, -2.0, -6.0, -5.0, -2.0, -3.0, -4.0])
x[1] = -1
x[6] = 1
x[0] = arr
x[7] = -arr

x

C:\Users\adany\AppData\Local\Temp\ipykernel_10840\732964940.py:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)
  x = torch.zeros(8,8)


tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [8]:
arr = torch.randint(0, 101, size=[20])
print(arr)
print(arr.sort().values[-2])
result = arr.sort().indices[-2]
result

tensor([55,  4, 12, 60, 99, 94,  8,  1, 95, 11, 39, 20, 25, 39, 61, 89, 25, 69,
        44, 92])
tensor(95)


tensor(8)

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [9]:
first_items = torch.arange(1, 8, step=1)
print(first_items)
second_items = torch.arange(0, 101, step=10).reshape(-1, 1)
print(second_items)
first_items + second_items

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[  0],
        [ 10],
        [ 20],
        [ 30],
        [ 40],
        [ 50],
        [ 60],
        [ 70],
        [ 80],
        [ 90],
        [100]])


tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [10]:
b_1d = torch.tensor([1,2,3])
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
res = a_2d - b_1d.reshape(b_1d.size()[0], 1)
res

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [17]:
import numpy

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [18]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

res = (a == b).nonzero(as_tuple=True)
list(res[0])

[tensor(1), tensor(3), tensor(5), tensor(7)]

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [20]:
arr = torch.arange(9).view(3,3)
arr = arr.flip(1).flip(0)
arr

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [21]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5) & (a <= 10)
res = a[mask]
res

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [22]:
res = torch.arange(9).reshape(3,3)
print(res)
res = res[:, [0, 2, 1]]
res

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [23]:
arr = torch.randint(0, 11, size=[8, 10])
print(arr)
item_index = arr.sum(axis=1).min(axis=0).indices.item()
print(item_index)
res = arr[item_index]
res

tensor([[ 2,  0,  9,  5,  9,  1,  1,  1,  5, 10],
        [ 2,  0,  4,  0,  1,  1,  4, 10,  4,  7],
        [ 8,  0,  7,  4,  6,  6,  6,  7,  6,  5],
        [ 8,  9,  0,  3,  0,  3,  2,  3,  5,  1],
        [ 8,  7,  2,  5,  1,  9,  3,  9,  0,  6],
        [ 8,  8, 10,  5,  8, 10,  6,  6,  8,  0],
        [ 2,  1, 10,  9,  7, 10,  4,  3,  0,  4],
        [ 5,  7,  3,  6,  0, 10,  7,  6,  2,  5]])
1


tensor([ 2,  0,  4,  0,  1,  1,  4, 10,  4,  7])

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [24]:
res = torch.randint(0, 101, size=[20])
print(res)
res[(res < 30)] = 30
print(res)
res[(res > 70)] = 70
res

tensor([62, 85, 80, 47, 79, 72, 86,  5, 41, 59, 34, 41, 33, 46, 93, 39,  0, 73,
        10, 99])
tensor([62, 85, 80, 47, 79, 72, 86, 30, 41, 59, 34, 41, 33, 46, 93, 39, 30, 73,
        30, 99])


tensor([62, 70, 70, 47, 70, 70, 70, 30, 41, 59, 34, 41, 33, 46, 70, 39, 30, 70,
        30, 70])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [26]:
a1 = torch.randint(0, 11, size=[30, 3])
a2 = torch.randint(0, 11, size=[30, 3])

mask = a1 > a2
print(a1[mask])

res = a1[mask].sum().item()
print(res)

tensor([ 2,  2,  2,  5,  9,  7,  7,  6,  7, 10,  9,  8,  5,  8,  7,  9,  9,  2,
         3,  9,  9,  8,  6,  5,  2,  8,  9,  4,  5,  9, 10,  9,  8,  5, 10,  6,
         5,  7,  5,  9,  8])
273


1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [28]:
res = torch.randint(0, 11, size=[20, 20])
print(res[torch.arange(19), torch.arange(19) +1])

tensor([4, 5, 0, 0, 5, 7, 9, 3, 9, 5, 5, 9, 6, 9, 0, 9, 8, 6, 4])


1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [30]:
a1 = torch.randint(0, 11, size=[5, 10])
a2 = torch.randint(0, 11, size=[5, 10])

mask = a1 == a2
a1[mask] = a1[mask] * 2
a1

tensor([[ 4,  2, 16,  7,  9,  4,  5,  5,  6, 10],
        [ 4,  5, 20,  1,  3,  7,  0,  5,  8, 12],
        [ 2,  6, 10,  3,  3, 10,  9,  8,  8,  1],
        [ 4,  9,  3,  8,  2,  3,  0,  8,  3,  8],
        [ 2,  0,  6,  9,  5,  2,  9,  7, 16,  9]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [31]:
a1 = torch.randint(0, 11, size=[4, 7])
a2 = torch.randint(0, 11, size=[4, 7])
a3 = torch.randint(0, 11, size=[4, 7])

mask = (a1 > a2) & (a1 < a3)
a1[mask] = 0
a1

tensor([[ 2,  4,  4,  1, 10,  0,  3],
        [ 4,  3,  5,  1,  0,  2,  0],
        [ 4,  8,  0,  5,  1,  7,  0],
        [ 3,  8,  9,  0,  9, 10,  5]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [34]:
a1 = torch.randint(0, 21, size=(20, 5))
condition = (a1.T == a1.max(axis=1).values).T.sum(axis=0) > 5
res = condition.nonzero(as_tuple=True)
res[0]

tensor([4])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [35]:
ar1 = torch.rand((4, 7))
print(ar1)
maximum = ar1.max().item()
print(maximum)

ar1[(ar1 == maximum).nonzero(as_tuple=True)[0][0] + 1:, (ar1 == maximum).nonzero(as_tuple=True)[1][0] + 1:] = 0
ar1

tensor([[0.6680, 0.3212, 0.0305, 0.3729, 0.0882, 0.2527, 0.7873],
        [0.2009, 0.3320, 0.7609, 0.1593, 0.9527, 0.4288, 0.6641],
        [0.1063, 0.6724, 0.1030, 0.7114, 0.1477, 0.0177, 0.1448],
        [0.8965, 0.0531, 0.4585, 0.5975, 0.0947, 0.5408, 0.6965]])
0.9527154564857483


tensor([[0.6680, 0.3212, 0.0305, 0.3729, 0.0882, 0.2527, 0.7873],
        [0.2009, 0.3320, 0.7609, 0.1593, 0.9527, 0.4288, 0.6641],
        [0.1063, 0.6724, 0.1030, 0.7114, 0.1477, 0.0000, 0.0000],
        [0.8965, 0.0531, 0.4585, 0.5975, 0.0947, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [36]:
arr = torch.tensor([2, 3, 2, 2, 2, 1])
res = torch.zeros(arr.size()[0], arr.max())
res[torch.arange(arr.size()[0]), arr-1] = 1
res

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [37]:
arr = torch.randint(0, 101, size=[20])
print(arr)
most_value = torch.mode(arr)[0]
print(most_value)
res = (arr == most_value).nonzero(as_tuple=True)[0].tolist()
res

tensor([95, 22, 59, 95,  2, 56, 72, 47,  4, 68, 44, 53,  3, 17, 12, 23, 18,  6,
        57, 18])
tensor(18)


[16, 19]

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 