In [120]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [121]:
class Neuron:
  def __init__(self, weights, bias):
    # <создать атрибуты объекта weights и bias>
    self.weights = weights
    self.bias = bias
    #pass
  
  def forward(self, inputs):
    return torch.sum(self.weights*inputs) + self.bias


In [122]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

In [123]:
neuron = Neuron(weights, bias)

res = neuron.forward(inputs)
res

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат.

In [124]:
class Linear:
  def __init__(self, weights, biases):
    self.weights = weights
    self.biases = biases
    #pass
  
  def forward(self, inputs):
    return torch.matmul(inputs, self.weights) + self.biases

In [125]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

In [126]:
linear = Linear(weights, biases)
res = linear.forward(inputs)
res

tensor([ 4.8400,  0.1700, 10.3900])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [127]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [128]:
res = linear.forward(inputs)
res

tensor([[ 3.7900,  0.9200,  9.0850],
        [ 6.1400, -2.1000,  6.9000],
        [ 2.0400,  0.7610,  6.7260]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [129]:
class Linear:
  def __init__(self, n_features, n_neurons):
    self.n_features = n_features
    self.n_neurons = n_neurons
    self.weights = torch.randn(self.n_features, self.n_neurons)
    self.biases = torch.randn(self.n_neurons)
    pass
  
  def forward(self, inputs):
    return torch.matmul(inputs, self.weights) + self.biases

In [130]:
linear = Linear(4, 3)
linear.forward(inputs)

tensor([[ 0.3190,  3.0288, -1.5835],
        [-2.3141, -3.2246, -4.7458],
        [-2.0571, -3.9855,  1.4061]])

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [131]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

linear_1 = Linear(4, 3)
linear_2 = Linear(3, 7)

linear_2.forward(linear_1.forward(inputs))

tensor([[  2.8364,   1.7682,  -1.2549,  -2.3819,  -1.4404,   1.2397,   1.8018],
        [  0.2004,   3.2024,  -7.2196, -14.9859,  -6.9387,   9.1500,  13.4043],
        [ -3.5855,   5.7864,   2.5832,  -4.6882,  -9.0695,  10.8442,  -2.7183]])

  ## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [132]:
class ReLU:
  def forward(self, inputs):
    mask = inputs < 0
    inputs[mask] = 0
    return inputs

In [133]:
relu = ReLU()
matr = torch.randn((4, 3))
res = relu.forward(matr)
print(res)

tensor([[0.0000, 0.0000, 1.4244],
        [0.0000, 0.5588, 0.0000],
        [0.0580, 0.0000, 0.0000],
        [1.3891, 0.7534, 0.3275]])


2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [134]:
class Softmax_c:
  def forward(self, inputs):
    matr = torch.exp(inputs)
    return matr/torch.sum(inputs, dim=1).view(-1,1)

In [135]:
sf = Softmax_c()
matr = torch.randn((4, 3))
res = sf.forward(matr)
print(res)

tensor([[ 1.4414,  0.2188,  4.0548],
        [ 1.8485, 17.3876,  0.3991],
        [ 3.8198,  1.5467,  2.4205],
        [76.7262, 35.7023, 13.0922]])


2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [136]:
class ELU:
  def __init__(self, alpha):
    self.alpha = alpha
    pass

  def forward(self, inputs):
    inputs[inputs < 0] = (torch.exp(inputs[inputs < 0]) - 1) * self.alpha
    return inputs

In [137]:
elu = ELU(alpha = 1)
matr = torch.randn((4, 3))
print("Input:\n", matr)

res = elu.forward(matr)
print("Output:\n", res)

Input:
 tensor([[ 0.8724,  1.7565,  0.7859],
        [-0.1431,  0.8570,  0.0966],
        [-1.8525,  0.5196,  0.2690],
        [-0.5411, -0.2260, -0.1513]])
Output:
 tensor([[ 0.8724,  1.7565,  0.7859],
        [-0.1333,  0.8570,  0.0966],
        [-0.8432,  0.5196,  0.2690],
        [-0.4179, -0.2023, -0.1404]])


## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [138]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return ((y_true - y_pred) ** 2).mean()

In [139]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

In [140]:
linear_layer = Linear(4, 1)

mse_loss = MSELoss()
res = mse_loss.forward(linear_layer.forward(inputs), y)
print(res)

tensor(27.8290)


2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [141]:
class CategoricalCrossentropyLoss:
  def forward(self, y_pred, y_true):
    return -1 * (y_true * torch.log(y_pred)).sum(1)
    pass

In [142]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

In [143]:
linear_layer = Linear(4, 3) #Слой с 3 нейронами

softmax = Softmax_c()
cce_loss = CategoricalCrossentropyLoss()
res = cce_loss.forward(softmax.forward(linear_layer.forward(inputs)), y)
print(res)

tensor([    nan, -0.4036,     nan])


2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [144]:
class MSELossL2:
    def __init__(self, lambda_, layer, W=0.1):
        self.lambda_ = lambda_
        self.layer = layer
        self.layer.W = W

    def data_loss(self, y_pred, y_true):
        return (y_true - y_pred) ** 2

    def reg_loss(self, layer):
        return self.lambda_ * (layer.W ** 2)

    def forward(self, y_pred, y_true):
        return self.data_loss(y_pred, y_true) + self.reg_loss(self.layer)

In [145]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

linear_layer = Linear(4, 3)
layer_out = linear_layer.forward(inputs)

softmax = Softmax_c()
mse_loss = MSELossL2(1.5, linear_layer)
res = mse_loss.forward(softmax.forward(layer_out), y)
print(res)

tensor([[1.4438e+02, 1.5034e-02, 1.6712e+02],
        [2.8172e+04, 1.5004e-02, 4.6064e+00],
        [1.6329e-02, 3.1593e+04, 1.5071e-02]])


## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [146]:
import sklearn

In [147]:
from sklearn.datasets import make_regression

In [148]:
X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5, random_state=0)
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).view(-1, 1)
y

tensor([[ -41.2726],
        [   4.2447],
        [ -95.1568],
        [ -24.5819],
        [  27.9462],
        [ -31.4934],
        [  55.9900],
        [-101.7946],
        [ -41.9318],
        [ 109.7482],
        [-115.0168],
        [ 102.2581],
        [ -64.1279],
        [ -29.8171],
        [-148.6656],
        [ -62.5905],
        [-111.8847],
        [-159.5456],
        [  23.4118],
        [  -7.6453],
        [  44.3271],
        [ 121.3781],
        [ 153.8689],
        [ 105.6647],
        [ -96.1774],
        [ -28.9994],
        [ 296.4494],
        [ -68.7938],
        [  52.0599],
        [  79.6068],
        [ 125.9714],
        [   2.0849],
        [  10.4737],
        [ 124.3630],
        [-150.6220],
        [  92.3236],
        [  -5.9085],
        [ 125.8456],
        [-199.2208],
        [-292.7495],
        [ 107.8483],
        [ -19.9285],
        [ 100.5492],
        [  94.9820],
        [-111.5261],
        [ -35.7181],
        [ 118.0920],
        [-219

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [149]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    return (y_pred - y_true) ** 2

  def backward(self, y_pred, y_true):
    self.dinput = 2 * (y_pred - y_true)


2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [150]:
class Neuron:
  def __init__(self, n_inputs: int):
    self.n_inputs = n_inputs
    self.weights = torch.randn(n_inputs)
    self.bias = torch.randn(1)
  
  def forward(self, inputs):
    self.inputs = inputs
    return (self.inputs * self.weights).sum() + self.bias
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    # df/dW
    self.dweights = dvalue * self.inputs
    # df/wX
    self.dinput =  dvalue * self.weights
    # df/db
    self.dbias = dvalue


In [151]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])

naive_neuron = Neuron(4)
out = naive_neuron.forward(inputs)
print(out)

tensor([-4.4917])


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [152]:
n_inputs = X.shape[1] # <размерность элемента выборки >
print(n_inputs)
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = SquaredLoss()

losses = []
for epoch in range(100):
  for x_example, y_example in zip(X, y):
    # нейрон
    y_pred =  neuron.forward(x_example)
    # функция потерь
    curr_loss = loss.forward(y_pred, y_example)
    losses.append(curr_loss)

    # обратите внимание на последовательность вызовов: от конца к началу
    #backward
    loss.backward(y_pred, y_example)
    neuron.backward(loss.dinput)

    # <шаг оптимизации для весов (weights и bias) нейрона>
    neuron.weights -= learning_rate * neuron.dweights
    neuron.bias -= learning_rate * neuron.dbias
losses[::20]

4


[tensor([1466.1143]),
 tensor([342.5593]),
 tensor([1.2629]),
 tensor([1.3692e-07]),
 tensor([3.6307e-06]),
 tensor([2.4178e-05]),
 tensor([1.1903e-06]),
 tensor([5.9605e-08]),
 tensor([9.0949e-11]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([2.3283e-10]),
 tensor([1.4552e-11]),
 tensor([3.2742e-11]),
 tensor([2.3283e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([1.4552e-11]),
 tensor([0.]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.])

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи: 
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами
 

In [153]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

  def backward(self, y_pred, y_true):
    self.dinput = 2 * (y_pred - y_true) / y_pred.shape[0] # df/dy^


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. 

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [154]:
class Neuron:
  def __init__(self, n_inputs):
    self.n_inputs = n_inputs
    self.weights = torch.randn(1, n_inputs).T
    self.bias = torch.randn(1)
  
  def forward(self, inputs):
    self.inputs = inputs
    return torch.matmul(inputs, self.weights) + self.bias
  
  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss)
    self.dinputs = torch.matmul(dvalue, self.weights.T)
    self.dweights = torch.matmul(self.inputs.T, dvalue) # df/dW
    self.dbias = torch.sum(dvalue) # df/db


2.4.2.3 Допишите цикл для настройки весов нейрона

In [155]:
n_inputs = X.shape[1] # размерность
learning_rate = 0.01 #  скорость
n_epoch = 1000 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()

losses = []

for epoch in range(n_epoch):
    # forward pass
    y_pred = neuron.forward(X) # нейрон
    curr_loss = loss.forward(y_pred, y) #функция потерь
    losses.append(curr_loss)


    #backward
    # обратите внимание на последовательность вызовов: от конца к началу
    loss.backward(y_pred, y)
    neuron.backward(loss.dinput)

    # <шаг оптимизации для весов (weights и bias) нейрона>
    neuron.weights -= learning_rate * neuron.dweights
    neuron.bias -= learning_rate * neuron.dbias

losses[::20]

[tensor(14387.2217),
 tensor(6112.7715),
 tensor(2649.1934),
 tensor(1174.4604),
 tensor(534.1511),
 tensor(249.8707),
 tensor(120.4514),
 tensor(59.8823),
 tensor(30.6870),
 tensor(16.1809),
 tensor(8.7543),
 tensor(4.8431),
 tensor(2.7301),
 tensor(1.5627),
 tensor(0.9055),
 tensor(0.5298),
 tensor(0.3124),
 tensor(0.1852),
 tensor(0.1104),
 tensor(0.0660),
 tensor(0.0396),
 tensor(0.0238),
 tensor(0.0143),
 tensor(0.0086),
 tensor(0.0052),
 tensor(0.0031),
 tensor(0.0019),
 tensor(0.0012),
 tensor(0.0007),
 tensor(0.0004),
 tensor(0.0003),
 tensor(0.0002),
 tensor(9.3870e-05),
 tensor(5.7004e-05),
 tensor(3.4591e-05),
 tensor(2.0998e-05),
 tensor(1.2809e-05),
 tensor(7.7580e-06),
 tensor(4.7027e-06),
 tensor(2.8949e-06),
 tensor(1.8024e-06),
 tensor(1.1127e-06),
 tensor(7.0796e-07),
 tensor(4.8205e-07),
 tensor(3.1544e-07),
 tensor(1.8797e-07),
 tensor(1.2597e-07),
 tensor(1.1551e-07),
 tensor(1.1416e-07),
 tensor(1.1121e-07)]

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [156]:
class Linear:
    def __init__(self, n_features, n_neurons):
        # <создать атрибуты объекта weights и biases>
        self.n_features = n_features
        self.n_neurons = n_neurons
        self.weights = torch.randn(n_neurons, n_features).T
        self.biases = torch.randn(n_neurons)

    def forward(self, inputs):
        self.inputs = inputs
        return torch.matmul(inputs, self.weights) + self.biases # <реализовать логику слоя>

    def backward(self, dvalues):
        self.dweights = torch.matmul(self.inputs.T, dvalues) # df/dW
        self.dbiases = torch.matmul(torch.ones(dvalues.shape[0]), dvalues) # df/db
        self.dinputs = torch.matmul(dvalues, self.weights.T) # df/dX

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

In [157]:
n_inputs = X.shape[1]  # <размерность элемента выборки >
learning_rate = 0.01  #  скорость обучения
n_epoch = 1000  #  количество эпох

layer = Linear(n_inputs, 1)
loss = MSELoss()

losses = []

for epoch in range(n_epoch):
    # forward pass
    y_pred = layer.forward(X)  # <прогон через нейрон>
    curr_loss = loss.forward(y_pred, y)  # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу
    loss.backward(y_pred, y)
    layer.backward(loss.dinput)

    # <шаг оптимизации для весов (weights и bias) нейрона>
    layer.weights -= learning_rate * layer.dweights
    layer.biases -= learning_rate * layer.dbiases

losses[::20]

[tensor(14447.3252),
 tensor(6157.1387),
 tensor(2678.4099),
 tensor(1192.7377),
 tensor(545.2997),
 tensor(256.5868),
 tensor(124.4738),
 tensor(62.2868),
 tensor(32.1240),
 tensor(17.0403),
 tensor(9.2691),
 tensor(5.1520),
 tensor(2.9156),
 tensor(1.6743),
 tensor(0.9728),
 tensor(0.5704),
 tensor(0.3368),
 tensor(0.2000),
 tensor(0.1193),
 tensor(0.0714),
 tensor(0.0428),
 tensor(0.0258),
 tensor(0.0155),
 tensor(0.0094),
 tensor(0.0056),
 tensor(0.0034),
 tensor(0.0021),
 tensor(0.0012),
 tensor(0.0008),
 tensor(0.0005),
 tensor(0.0003),
 tensor(0.0002),
 tensor(0.0001),
 tensor(6.1975e-05),
 tensor(3.7619e-05),
 tensor(2.2861e-05),
 tensor(1.3902e-05),
 tensor(8.4315e-06),
 tensor(5.1295e-06),
 tensor(3.1487e-06),
 tensor(1.9529e-06),
 tensor(1.2146e-06),
 tensor(7.5568e-07),
 tensor(5.1350e-07),
 tensor(3.3873e-07),
 tensor(2.0924e-07),
 tensor(1.3107e-07),
 tensor(1.1485e-07),
 tensor(1.1481e-07),
 tensor(1.1184e-07)]

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура: 
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [158]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size()) 

In [159]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output
  
  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [160]:
# создание компонентов сети
fc1 = Linear(X.shape[1], 10)
relu1 = Activation_ReLU()
fc2 = Linear(10, 1)

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
    # <forward pass>
    y_pred = fc2.forward(relu1.forward(fc1.forward(X)))

    data_loss = loss.forward(y_pred, y) # <прогон через функцию потерь>

    if epoch % 200 == 0:
        print(f'epoch {epoch} mean loss {data_loss}')
        ys.append(y_pred)

    # <backprop>
    # loss > fc2 > relu1 > fc1
    loss.backward(y_pred, y)
    fc2.backward(loss.dinput)
    relu1.backward(fc2.dinputs)
    fc1.backward(relu1.dinputs)

    # <шаг оптимизации для fc1>
    fc1.weights -= lr * fc1.dweights
    fc1.biases -= lr * fc1.dbiases

    # <шаг оптимизации для fc2>
    fc2.weights -= lr * fc2.dweights
    fc2.biases -= lr * fc2.dbiases

epoch 0 mean loss 3.6640965938568115
epoch 200 mean loss 0.05424844101071358
epoch 400 mean loss 0.032951656728982925
epoch 600 mean loss 0.020990218967199326
epoch 800 mean loss 0.014961766079068184
epoch 1000 mean loss 0.012281829491257668
epoch 1200 mean loss 0.011160657741129398
epoch 1400 mean loss 0.010714847594499588
epoch 1600 mean loss 0.010542060248553753
epoch 1800 mean loss 0.010476239025592804
epoch 2000 mean loss 0.010413460433483124


In [161]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
    ax.scatter(X.numpy(), y.numpy(), color="red")
    ax.plot(X.numpy(), y_.numpy(), 'blue', lw=3)
    ax.set_xlim(-1.05, 1.5)
    ax.set_ylim(-0.25, 1.25)

ModuleNotFoundError: No module named 'matplotlib'