In [56]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [57]:
class Neuron:
  def __init__(self, weights, bias):
    # <создать атрибуты объекта weights и bias>
    self.weights = weights
    self.bias = bias
    #pass
  
  def forward(self, inputs):
    return torch.sum(self.weights*inputs) + self.bias


In [58]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

In [59]:
neuron = Neuron(weights, bias)

res = neuron.forward(inputs)
res

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат.

In [60]:
class Linear:
  def __init__(self, weights, biases):
    self.weights = weights
    self.biases = biases
    #pass
  
  def forward(self, inputs):
    return torch.matmul(inputs, self.weights) + self.biases

In [61]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

In [62]:
linear = Linear(weights, biases)
res = linear.forward(inputs)
res

tensor([ 4.8400,  0.1700, 10.3900])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [63]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [64]:
res = linear.forward(inputs)
res

tensor([[ 3.7900,  0.9200,  9.0850],
        [ 6.1400, -2.1000,  6.9000],
        [ 2.0400,  0.7610,  6.7260]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [65]:
class Linear:
  def __init__(self, n_features, n_neurons):
    self.n_features = n_features
    self.n_neurons = n_neurons
    self.weights = torch.randn(self.n_features, self.n_neurons)
    self.biases = torch.randn(self.n_neurons)
    pass
  
  def forward(self, inputs):
    return torch.matmul(inputs, self.weights) + self.biases

In [66]:
linear = Linear(4, 3)
linear.forward(inputs)

tensor([[-1.8101,  8.6537,  4.0937],
        [ 1.4962, -1.2842,  3.4435],
        [ 1.8217,  7.4116,  2.2414]])

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [67]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

linear_1 = Linear(4, 3)
linear_2 = Linear(3, 7)

linear_2.forward(linear_1.forward(inputs))

tensor([[  9.9509,   7.7411,   4.4733,   5.0301,   3.3596,  14.2657,   5.2831],
        [ 16.8953,   1.7149, -13.4990,   0.0608,  -3.7141,  26.3046,  12.4055],
        [  4.2300,  10.5011,  20.2487,   6.8382,   8.2724,   3.5464,   8.7085]])

  ## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [68]:
class ReLU:
  def forward(self, inputs):
    mask = inputs < 0
    inputs[mask] = 0
    return inputs

In [69]:
relu = ReLU()
matr = torch.randn((4, 3))
res = relu.forward(matr)
print(res)

tensor([[0.0000, 0.4852, 0.0000],
        [1.2609, 0.0000, 0.0000],
        [1.1314, 1.5944, 0.0745],
        [0.0000, 0.0000, 1.9929]])


2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [70]:
class Softmax_c:
  def forward(self, inputs):
    matr = torch.exp(inputs)
    return matr/torch.sum(inputs, dim=1).view(-1,1)

In [71]:
sf = Softmax_c()
matr = torch.randn((4, 3))
res = sf.forward(matr)
print(res)

tensor([[ -2.4668,  -0.0446,  -0.4710],
        [ -1.0709,  -2.0452, -15.2172],
        [  0.3803,   0.3954,   5.0436],
        [  2.4555,   0.4762,   2.0623]])


2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [72]:
class ELU:
  def __init__(self, alpha):
    self.alpha = alpha
    pass

  def forward(self, inputs):
    inputs[inputs < 0] = (torch.exp(inputs[inputs < 0]) - 1) * self.alpha
    return inputs

In [73]:
elu = ELU(alpha = 1)
matr = torch.randn((4, 3))
print("Input:\n", matr)

res = elu.forward(matr)
print("Output:\n", res)

Input:
 tensor([[-0.4468, -2.8943,  0.1120],
        [-0.0720, -0.1327, -1.1924],
        [-1.3818,  0.2383,  0.8949],
        [ 0.7810,  1.2252,  0.5714]])
Output:
 tensor([[-0.3604, -0.9447,  0.1120],
        [-0.0694, -0.1243, -0.6965],
        [-0.7489,  0.2383,  0.8949],
        [ 0.7810,  1.2252,  0.5714]])


## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [74]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return ((y_true - y_pred) ** 2).mean()

In [75]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

In [76]:
linear_layer = Linear(4, 1)

mse_loss = MSELoss()
res = mse_loss.forward(linear_layer.forward(inputs), y)
print(res)

tensor(5.3595)


2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [77]:
class CategoricalCrossentropyLoss:
  def forward(self, y_pred, y_true):
    return -1 * (y_true * torch.log(y_pred)).sum(1)
    pass

In [78]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

In [79]:
linear_layer = Linear(4, 3) #Слой с 3 нейронами

softmax = Softmax_c()
cce_loss = CategoricalCrossentropyLoss()
res = cce_loss.forward(softmax.forward(linear_layer.forward(inputs)), y)
print(res)

tensor([-6.9740, -7.0203, -3.4153])


2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [80]:
class MSELossL2:
    def __init__(self, lambda_, layer, W=0.1):
        self.lambda_ = lambda_
        self.layer = layer
        self.layer.W = W

    def data_loss(self, y_pred, y_true):
        return (y_true - y_pred) ** 2

    def reg_loss(self, layer):
        return self.lambda_ * (layer.W ** 2)

    def forward(self, y_pred, y_true):
        return self.data_loss(y_pred, y_true) + self.reg_loss(self.layer)

In [81]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

linear_layer = Linear(4, 3)
layer_out = linear_layer.forward(inputs)

softmax = Softmax_c()
mse_loss = MSELossL2(1.5, linear_layer)
res = mse_loss.forward(softmax.forward(layer_out), y)
print(res)

tensor([[8.9316e-01, 1.7339e-02, 1.1416e+02],
        [9.7086e-01, 1.9341e+03, 2.3317e+00],
        [2.8711e+04, 1.5001e-02, 2.4423e+06]])


## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [82]:
import sklearn

In [83]:
from sklearn.datasets import make_regression

In [84]:
X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5, random_state=0)
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).view(-1, 1)
X

tensor([[-0.5097, -0.4381, -1.2528,  0.7775],
        [-0.6743,  0.0318, -0.6358,  0.6764],
        [-0.8878, -1.9808, -0.3479,  0.1563],
        [ 1.9559,  0.3901, -0.6524, -0.3910],
        [ 0.0977,  0.5830, -0.3994,  0.3701],
        [-1.8431, -0.4780, -0.4797,  0.6204],
        [ 0.8416, -0.2495,  0.0495,  0.4938],
        [-0.7196, -0.8130,  0.2745, -0.8909],
        [-0.0157,  0.1609, -0.1907, -0.3948],
        [-0.3090, -1.6760,  1.1523,  1.0796],
        [-0.7256, -1.3834, -1.5829,  0.6104],
        [ 2.3039, -1.0600, -0.1359,  1.1369],
        [ 0.5766, -0.2083,  0.3960, -1.0931],
        [ 1.4941, -0.2052,  0.3131, -0.8541],
        [-0.3534, -1.6165, -0.2918, -0.7615],
        [ 0.0665,  0.3025, -0.6343, -0.3627],
        [-0.2677, -1.1280,  0.2804, -0.9931],
        [-0.5973, -0.2379, -1.4241, -0.4933],
        [ 0.6433, -1.5706, -0.2069,  0.8802],
        [ 1.8832, -1.3478, -1.2705,  0.9694],
        [-0.9073,  0.0519,  0.7291,  0.1290],
        [-0.1105,  1.0202, -0.6920

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [85]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    return (y_pred - y_true) ** 2

  def backward(self, y_pred, y_true):
    self.dinput = 2 * (y_pred - y_true)


2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [86]:
class Neuron:
  def __init__(self, n_inputs: int):
    self.n_inputs = n_inputs
    self.weights = torch.randn(n_inputs)
    self.bias = torch.randn(1)
  
  def forward(self, inputs):
    self.inputs = inputs
    return (self.inputs * self.weights).sum() + self.bias
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    # df/dW
    self.dweights = dvalue * self.inputs
    # df/wX
    self.dinput =  dvalue * self.weights
    # df/db
    self.dbias = dvalue


In [87]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])

naive_neuron = Neuron(4)
out = naive_neuron.forward(inputs)
print(out)

tensor([-2.4518])


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [88]:
n_inputs = X.shape[1] # <размерность элемента выборки >
print(n_inputs)
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = SquaredLoss()

losses = []
for epoch in range(100):
  for x_example, y_example in zip(X, y):
    # нейрон
    y_pred =  neuron.forward(x_example)
    # функция потерь
    curr_loss = loss.forward(y_pred, y_example)
    losses.append(curr_loss)

    # обратите внимание на последовательность вызовов: от конца к началу
    #backward
    loss.backward(y_pred, y_example)
    neuron.backward(loss.dinput)

    # <шаг оптимизации для весов (weights и bias) нейрона>
    neuron.weights -= learning_rate * neuron.dweights
    neuron.bias -= learning_rate * neuron.dbias
losses[::20]

4


[tensor([2138.7148]),
 tensor([358.7410]),
 tensor([1.4164]),
 tensor([1.2858e-07]),
 tensor([3.5225e-06]),
 tensor([2.7472e-05]),
 tensor([1.3272e-06]),
 tensor([6.7288e-08]),
 tensor([0.]),
 tensor([3.6380e-12]),
 tensor([5.8208e-11]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([0.]),
 tensor([1.3097e-10]),
 tensor([1.4552e-11]),
 tensor([5.8208e-11]),
 tensor([0.]),
 tensor([0.]),
 tensor([7.1304e-10]),
 tensor([0.]),
 tensor([2.3283e-10]),
 tensor([1.4552e-11]),
 tensor([3.2742e-11]),
 tensor([2.3283e-10]),
 tensor([0.]),
 tensor([2.3283e-10]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.8208e-11]),
 tensor([3.6380e-12]),
 tensor([3.6380e-12]),
 tensor([5.2387e-10]),
 tensor([0.]),
 tensor([5.820

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи: 
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами
 

In [89]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

  def backward(self, y_pred, y_true):
    self.dinput = 2 * (y_pred - y_true) / y_pred.shape[0] # df/dy^


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. 

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [90]:
class Neuron:
  def __init__(self, n_inputs):
    self.n_inputs = n_inputs
    self.weights = torch.randn(1, n_inputs).T
    self.bias = torch.randn(1)
  
  def forward(self, inputs):
    self.inputs = inputs
    return torch.matmul(inputs, self.weights) + self.bias
  
  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss)
    self.dinputs = torch.matmul(dvalue, self.weights.T)
    self.dweights = torch.matmul(self.inputs.T, dvalue) # df/dW
    self.dbias = torch.sum(dvalue) # df/db


2.4.2.3 Допишите цикл для настройки весов нейрона

In [91]:
n_inputs = X.shape[1] # размерность
learning_rate = 0.01 #  скорость
n_epoch = 1000 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()

losses = []

for epoch in range(n_epoch):
    # forward pass
    y_pred = neuron.forward(X) # нейрон
    curr_loss = loss.forward(y_pred, y) #функция потерь
    losses.append(curr_loss)


    #backward
    # обратите внимание на последовательность вызовов: от конца к началу
    loss.backward(y_pred, y)
    neuron.backward(loss.dinput)

    # <шаг оптимизации для весов (weights и bias) нейрона>
    neuron.weights -= learning_rate * neuron.dweights
    neuron.bias -= learning_rate * neuron.dbias

losses[::20]

[tensor(14383.0850),
 tensor(6161.0527),
 tensor(2693.2324),
 tensor(1204.8553),
 tensor(553.1680),
 tensor(261.2742),
 tensor(127.1657),
 tensor(63.8119),
 tensor(32.9872),
 tensor(17.5316),
 tensor(9.5510),
 tensor(5.3154),
 tensor(3.0112),
 tensor(1.7307),
 tensor(1.0062),
 tensor(0.5904),
 tensor(0.3488),
 tensor(0.2073),
 tensor(0.1237),
 tensor(0.0740),
 tensor(0.0444),
 tensor(0.0267),
 tensor(0.0161),
 tensor(0.0097),
 tensor(0.0059),
 tensor(0.0035),
 tensor(0.0021),
 tensor(0.0013),
 tensor(0.0008),
 tensor(0.0005),
 tensor(0.0003),
 tensor(0.0002),
 tensor(0.0001),
 tensor(6.4311e-05),
 tensor(3.9064e-05),
 tensor(2.3756e-05),
 tensor(1.4415e-05),
 tensor(8.7592e-06),
 tensor(5.3504e-06),
 tensor(3.2811e-06),
 tensor(2.0157e-06),
 tensor(1.2647e-06),
 tensor(7.8168e-07),
 tensor(5.2781e-07),
 tensor(3.5335e-07),
 tensor(2.1805e-07),
 tensor(1.3391e-07),
 tensor(1.1484e-07),
 tensor(1.1479e-07),
 tensor(1.1185e-07)]

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [92]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику слоя>

  def backward(self, dvalues):
    self.dweights = # df/dW
    self.dbiases = # df/db
    self.dinputs = # df/dX

SyntaxError: invalid syntax (3719429702.py, line 10)

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура: 
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [ ]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size()) 

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output
  
  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [ ]:
# создание компонентов сети
# fc1 = 
# relu1 = 
# fc2 = 

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
  # <forward pass>
  # fc1 > relu1 > fc2 > loss

  data_loss = # <прогон через функцию потерь>

  if epoch % 200 == 0:
    print(f'epoch {epoch} mean loss {data_loss}')
    ys.append(out)
  
  # <backprop> 
  # loss > fc2 > relu1 > fc1

  # <шаг оптимизации для fc1>

  # <шаг оптимизации для fc2>


In [ ]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
  ax.scatter(X.numpy(), y.numpy(), color = "orange")
  ax.plot(X.numpy(), y_.numpy(), 'g-', lw=3)
  ax.set_xlim(-1.05, 1.5)
  ax.set_ylim(-0.25, 1.25)